/* autogenerated by Processing revision 1304 on 2025-10-14 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Calculator1 extends PApplet {

// Sadikshya Kuikel | 09/25/25 | calculator
Button [] buttons = new Button[13];
Button[] numButtons = new Button[10];
float l, r, result;
String dVal;
char op;
boolean left;

public void setup() {
  /* size commented out by preprocessor */;
  l = 0.0f;
  r = 0.0f;
  result = 0.0f;
  dVal = "0.0";
  op = ' ';
  left = true;

  buttons[0] = new Button (40, 105, 40, 40, 'C', 0xFFF2A1BB, 0xFFD68AA2);
  numButtons[0] = new Button (70, 340, 100, 40, '0', 0xFFFFDBE6, 0xFFE8BECB);
  buttons[1] = new Button (100, 105, 40, 40, '±', 0xFFF2A1BB, 0xFFD68AA2);
  buttons[2] = new Button (160, 105, 40, 40, '^', 0xFFF2A1BB, 0xFFD68AA2);
  buttons[3] = new Button (220, 105, 40, 40, '²', 0xFFF2A1BB, 0xFFD68AA2);
  buttons[4] = new Button (280, 105, 40, 40, '√', 0xFFF2A1BB, 0xFFD68AA2);
  numButtons[7] = new Button (40, 165, 40, 40, '7', 0xFFFFDBE6, 0xFFE8BECB);
  numButtons[8] = new Button (100, 165, 40, 40, '8', 0xFFFFDBE6, 0xFFE8BECB);
  numButtons[9] = new Button (160, 165, 40, 40, '9', 0xFFFFDBE6, 0xFFE8BECB);
  buttons[5] = new Button (220, 165, 40, 40, '÷', 0xFFF2A1BB, 0xFFD68AA2);
  buttons[6] = new Button (280, 165, 40, 40, 's', 0xFFF2A1BB, 0xFFD68AA2);
  numButtons[4] = new Button (40, 225, 40, 40, '4', 0xFFFFDBE6, 0xFFE8BECB);
  numButtons[5] = new Button (100, 225, 40, 40, '5', 0xFFFFDBE6, 0xFFE8BECB);
  numButtons[6] = new Button (160, 225, 40, 40, '6', 0xFFFFDBE6, 0xFFE8BECB);
  buttons[7] = new Button (220, 225, 40, 40, 'x', 0xFFF2A1BB, 0xFFD68AA2);
  buttons[8] = new Button (280, 225, 40, 40, 't', 0xFFF2A1BB, 0xFFD68AA2);
  numButtons[1] = new Button (40, 285, 40, 40, '1', 0xFFFFDBE6, 0xFFE8BECB);
  numButtons[2] = new Button (100, 285, 40, 40, '2', 0xFFFFDBE6, 0xFFE8BECB);
  numButtons[3] = new Button (160, 285, 40, 40, '3', 0xFFFFDBE6, 0xFFE8BECB);
  buttons[9] = new Button (220, 285, 40, 40, '+', 0xFFF2A1BB, 0xFFD68AA2);
  buttons[10] = new Button (280, 315, 40, 100, '=', 0xFFF2A1BB, 0xFFD68AA2);
  buttons[11] = new Button (160, 340, 40, 40, '.', 0xFFFFDBE6, 0xFFE8BECB);
  buttons[12] = new Button (220, 340, 40, 40, '-', 0xFFF2A1BB, 0xFFD68AA2);
}

public void draw () {
  background(0xFFFFF2F6);
  for (int i = 0; i<buttons.length; i++) {
    buttons[i].display();
    buttons[i].hover(mouseX, mouseY);
  }
  for (int i = 0; i<numButtons.length; i++) {
    numButtons[i].display();
    numButtons[i].hover(mouseX, mouseY);
  }
  updateDisplay();
}

public void mousePressed() {
  for (int i = 0; i<buttons.length; i++) {
    if (!buttons[i].over) continue;

    char v = buttons[i].val;

    if (v == '+') {
      dVal = "0.0";
      left = false;
      op = '+';
    } else if (v == '-') {
      dVal = "0.0";
      left = false;
      op = '-';
    } else if (v == 'x') {
      dVal = "0.0";
      left = false;
      op = '*';
    } else if (v == '÷') {
      dVal = "0.0";
      left = false;
      op = '/';
    } else if (v == '^') {
      dVal = "0.0";
      left = false;
      op = '^';
    } else if (v == '=') {
      performCalculation();
    } else if (v == '²') {
      if (left) {
        l = sq(l);
        dVal = str(l);
      } else {
        r = sq(r);
        dVal = str(r);
      }
    } else if (v == '√') {
      if (left) {
        l = sqrt(l);
        dVal = str(l);
      } else {
        r = sqrt(r);
        dVal = str(r);
      }
    } else if (v == '.') {
      if (!dVal.contains(".")) dVal += ".";
    } else if (v == '±') {
      if (left) {
        l *= -1;
        dVal = str(l);
      } else {
        r *= -1;
        dVal = str(r);
      }
    } else if (v == 't') {
      if (left) {
        l = tan(radians(l));
        dVal = str(l);
      } else {
        r = tan(radians(r));
        dVal = str(r);
      }
    } else if (v == 's') {
      if (left) {
        l = sin(radians(l));
        dVal = str(l);
      } else {
        r = sin(radians(r));
        dVal = str(r);
      }
    } else if (v == 'C') {
      l = 0.0f;
      r = 0.0f;
      result = 0.0f;
      dVal = "0.0";
      op = ' ';
      left = true;
    }
  }

  for (int i = 0; i<numButtons.length; i++) {
    if (!numButtons[i].over) continue;
    if (dVal.length() < 18) {
      if (left) {
        if (dVal.equals("0.0")) dVal = str(numButtons[i].val);
        else dVal += str(numButtons[i].val);
        l = PApplet.parseFloat(dVal);
      } else {
        if (dVal.equals("0.0")) dVal = str(numButtons[i].val);
        else dVal += str(numButtons[i].val);
        r = PApplet.parseFloat(dVal);
      }
    }
  }

  println("l:" + l + " r:" + r + " result:" + result + " op:" + op + " left:" + left);
}

public void updateDisplay() {
  rectMode(CORNER);
  fill (0xFFFCF5F7);
  rect(20, 20, 280, 40, 4);
  textAlign(RIGHT);
  fill(0xFFB92F59);
  textSize(30);
  text(dVal, width-25, 50);
}

public void performCalculation() {
  if (op == '+') result = l + r;
  else if (op == '-')
    result = l - r;
  else if (op == '*')
    result = l * r;
  else if (op == '/')
    result = (r != 0) ? l / r : 0;
  else if (op == '^') result = pow(l, r);

  dVal = str(result);
  l = result;
  left = true;
}
class Button {
  int x, y, w, h;
  int c1, c2;
  char val;
  boolean over;

  Button(int x, int y, int w, int h, char val, int c1, int c2) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.val = val;
    this.c1 = c1;
    this.c2 = c2;
    over = false;
  }

  public void display () {
    rectMode(CENTER);
    fill(over ? c2 : c1);
    rect(x, y, w, h, 4);
    fill(0xFFB92F59);
    textSize(20);
    textAlign(CENTER, CENTER);
    text(val, x, y);
  }

  public void hover(int tempX, int tempY) {
    over = (tempX > x-w/2 && tempX < x+w/2 && tempY > y-h/2 && tempY < y+h/2);
  }
}


  public void settings() { size(320, 380); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Calculator1" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
